#!/usr/bin/env bash
# Holocron — Claude Code harness validation script
# Runs all checks from claude/ValidateClaudeCLI.md and prints a summary.
# Usage: bash claude/validate-claude-cli.sh
#
# Rewritten 2026-09-01 (spec 001 follow-up) for the single-harness Claude
# Code + pi layout: CLAUDE.md is a generated concatenation (no @-imports),
# skills/agents are real merge-linked directories (not top-level symlinks),
# and hook checks are read dynamically from settings.json instead of a
# hardcoded opencode-path list. For machine-wide pointer drift (skills,
# agents, instructions, settings precedence), prefer `install.sh --check` —
# this script covers Claude-specific content correctness that install.sh
# doesn't classify (import resolution, hook wiring, MCP registration).

set -uo pipefail

PASS=0
FAIL=0
INFO=0

ok()   { echo "  ✓  $1"; PASS=$((PASS+1)); }
fail() { echo "  ✗  $1"; FAIL=$((FAIL+1)); }
info() { echo "  ℹ  $1"; INFO=$((INFO+1)); }

section() { echo ""; echo "── $1 ──────────────────────────────────────────"; }

# ── 1. Core config files ─────────────────────────────────────────────────────

section "1. Core config files"

[[ -L ~/.claude/CLAUDE.md ]]      && ok "CLAUDE.md is a symlink"         || fail "CLAUDE.md missing or not a symlink — run install.sh"
[[ -f ~/.claude/CLAUDE.md ]]      && ok "CLAUDE.md target exists"         || fail "CLAUDE.md symlink is broken"
grep -q "^<!-- GENERATED by install.sh" ~/.claude/CLAUDE.md 2>/dev/null && ok "CLAUDE.md has the GENERATED header" || fail "CLAUDE.md missing the GENERATED header — stale copy or hand-edited?"
[[ -L ~/.claude/settings.json ]]  && ok "settings.json is a symlink"     || fail "settings.json missing or not a symlink — run install.sh"
python3 -m json.tool ~/.claude/settings.json > /dev/null 2>&1 && ok "settings.json is valid JSON" || fail "settings.json is invalid JSON"

# ── 2. Canonical content resolution ──────────────────────────────────────────
# CLAUDE.md is a generated concatenation, not an @-import shim (Claude's
# external-@-import consent gate made a hand-written shim unreliable across
# new projects — see DECISIONS.md / research.md R1). Verify it actually
# contains the canonical file's content rather than checking for @-imports
# that no longer exist.

section "2. Canonical content resolution"

grep -q "^## Execution Modes" ~/.claude/CLAUDE.md 2>/dev/null \
  && ok "CLAUDE.md contains the canonical AGENTS.md content (Execution Modes section found)" \
  || fail "CLAUDE.md does not contain AGENTS.md content — regeneration may have failed, run install.sh"

grep -q "HOLocrON-MARKER-001" ~/.claude/CLAUDE.md 2>/dev/null \
  && ok "CLAUDE.md contains the standing canonical-file marker" \
  || fail "CLAUDE.md missing HOLocrON-MARKER-001 — instructions/AGENTS.md may be out of sync"

grep -q "Session naming" ~/.claude/CLAUDE.md 2>/dev/null \
  && ok "CLAUDE.md contains the Claude-only tail (claude-tail.md)" \
  || fail "CLAUDE.md missing claude-tail.md content"

install_check_out=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && bash install.sh --check 2>&1)
install_check_rc=$?
if echo "$install_check_out" | grep -q "CLAUDE.md"; then
  fail "install.sh --check reports CLAUDE.md as stale — run install.sh to regenerate"
else
  ok "install.sh --check reports CLAUDE.md fresh (no regeneration needed)"
fi

# ── 3. Skills and commands ───────────────────────────────────────────────────
# skills/ and agents/ are merge-linked real directories (whole-dir symlinks
# per skill/per-file symlinks per agent), not top-level symlinks themselves —
# only commands/ and instructions/ are still plain directory symlinks.

section "3. Skills and commands"

[[ -d ~/.claude/skills && ! -L ~/.claude/skills ]] \
  && ok "~/.claude/skills is a real directory (merge-linked)" \
  || fail "~/.claude/skills missing or still a symlink — run install.sh"

SKILL_COUNT=$(find ~/.claude/skills -maxdepth 1 -mindepth 1 2>/dev/null | wc -l | tr -d ' ')
[[ "$SKILL_COUNT" -gt 0 ]] && ok "$SKILL_COUNT skill(s) found" || fail "No skills found — check ~/.claude/skills/"

LOWERCASE_VIOLATIONS=$(find ~/.claude/skills -maxdepth 1 -mindepth 1 2>/dev/null | xargs -n1 basename 2>/dev/null | grep -Ev '^[a-z0-9-]+$' || true)
if [[ -z "$LOWERCASE_VIOLATIONS" ]]; then
  ok "all skill directory names are lowercase-hyphen (Agent Skills standard)"
else
  fail "non-compliant skill name(s) found (should be lowercase-hyphen): $LOWERCASE_VIOLATIONS"
fi

[[ -L ~/.claude/commands ]] && ok "~/.claude/commands is a symlink" || fail "~/.claude/commands is not a symlink — run install.sh"
[[ -d ~/.claude/commands ]] && ok "~/.claude/commands target exists" || fail "~/.claude/commands symlink is broken"

CMD_COUNT=$(ls ~/.claude/commands/*.md 2>/dev/null | grep -vc ".gitkeep" || true)
[[ "$CMD_COUNT" -gt 0 ]] && ok "$CMD_COUNT command(s) found" || fail "No command files found — check symlink target"

[[ -L ~/.claude/instructions ]] && ok "~/.claude/instructions is a symlink" || fail "~/.claude/instructions is not a symlink — run install.sh"
[[ -f ~/.claude/instructions/algorithm.md ]] && ok "~/.claude/instructions/algorithm.md resolves" || fail "~/.claude/instructions/algorithm.md missing — check the instructions/ symlink"

# ── 4. Agents ────────────────────────────────────────────────────────────────

section "4. Agents"

[[ -d ~/.claude/agents && ! -L ~/.claude/agents ]] \
  && ok "~/.claude/agents is a real directory (merge-linked)" \
  || fail "~/.claude/agents missing or still a symlink — run install.sh"

AGENT_COUNT=$(ls ~/.claude/agents/*.md 2>/dev/null | wc -l | tr -d ' ')
[[ "$AGENT_COUNT" -ge 15 ]] \
  && ok "$AGENT_COUNT agent(s) found in ~/.claude/agents/" \
  || fail "Expected 15+ agents, found $AGENT_COUNT — check repo agents/ directory"

DANGLING_AGENTS=0
for f in ~/.claude/agents/*.md; do
  [[ -e "$f" ]] || DANGLING_AGENTS=$((DANGLING_AGENTS+1))
done
[[ "$DANGLING_AGENTS" -eq 0 ]] && ok "no dangling agent symlinks" || fail "$DANGLING_AGENTS dangling agent symlink(s) found — run install.sh"

# ── 5. Environment variables ──────────────────────────────────────────────────

section "5. Environment variables"

MEM_DIR=$(python3 -c "
import json, os
try:
  d = json.load(open(os.path.expanduser('~/.claude/settings.json')))
  print(d.get('env', {}).get('HOLOCRON_MEMORY_DIR', ''))
except: pass
" 2>/dev/null)

if [[ -n "$MEM_DIR" ]]; then
  ok "HOLOCRON_MEMORY_DIR set in settings.json: $MEM_DIR"
  [[ -d "$MEM_DIR" ]] && ok "HOLOCRON_MEMORY_DIR path exists on disk" || fail "HOLOCRON_MEMORY_DIR path does not exist: $MEM_DIR"
else
  fail "HOLOCRON_MEMORY_DIR missing from settings.json env block"
fi

CONFIG_DIR=$(python3 -c "
import json, os
try:
  d = json.load(open(os.path.expanduser('~/.claude/settings.json')))
  print(d.get('env', {}).get('HOLOCRON_CONFIG_DIR', ''))
except: pass
" 2>/dev/null)

if [[ -n "$CONFIG_DIR" ]]; then
  if [[ "$CONFIG_DIR" == *"/.config/opencode"* ]]; then
    fail "HOLOCRON_CONFIG_DIR still points at the retired ~/.config/opencode/ ($CONFIG_DIR) — point it at ~/.claude instead"
  elif [[ -d "$CONFIG_DIR" ]]; then
    ok "HOLOCRON_CONFIG_DIR set and exists: $CONFIG_DIR"
  else
    fail "HOLOCRON_CONFIG_DIR path does not exist: $CONFIG_DIR"
  fi
else
  info "HOLOCRON_CONFIG_DIR not set in settings.json (optional — only used by a few skill tools as a .env fallback)"
fi

# ── 6. Hook scripts ───────────────────────────────────────────────────────────
# Read every hook command actually wired in settings.json (rather than a
# hardcoded list at a dead opencode path) and verify each referenced script
# file exists and, for bash scripts, is executable.

section "6. Hook scripts"

while IFS=$'\t' read -r kind msg; do
  case "$kind" in
    OK)   ok "$msg" ;;
    FAIL) fail "$msg" ;;
    INFO) info "$msg" ;;
  esac
done < <(python3 <<'PYEOF'
import json, os, re, sys

settings_path = os.path.expanduser("~/.claude/settings.json")
try:
    d = json.load(open(settings_path))
except Exception as e:
    print(f"FAIL\tCould not parse settings.json: {e}")
    sys.exit(0)

hooks = d.get("hooks", {})
if not hooks:
    print("FAIL\tNo hooks block found in settings.json")
    sys.exit(0)

seen = set()
for event, entries in hooks.items():
    for entry in entries:
        for h in entry.get("hooks", []):
            cmd = h.get("command", "")
            if not cmd or cmd in seen:
                continue
            seen.add(cmd)
            m = re.search(r'([~$][^\s]*\.(?:sh|ts))', cmd)
            if not m:
                print(f"INFO\t{event}: command has no recognizable script path: {cmd}")
                continue
            raw_path = m.group(1)
            path = raw_path.replace("~", os.path.expanduser("~"))
            path = os.path.expandvars(path)
            if not os.path.isabs(path):
                print(f"INFO\t{event}: could not resolve variable path: {raw_path}")
                continue
            if not os.path.isfile(path):
                print(f"FAIL\t{event}: hook script missing: {path}")
                continue
            if path.endswith(".sh") and not os.access(path, os.X_OK):
                print(f"FAIL\t{event}: hook script not executable: {path} (chmod +x)")
                continue
            suffix = " and is executable" if path.endswith(".sh") else ""
            print(f"OK\t{event}: {os.path.basename(path)} exists{suffix}")

print(f"INFO\t{len(seen)} unique hook command(s) checked across {len(hooks)} event(s)")
PYEOF
)

# ── 7. No stale ~/.config/claude symlink ─────────────────────────────────────

section "7. No stale ~/.config/claude symlink"

[[ ! -e ~/.config/claude ]] \
  && ok "~/.config/claude does not exist (correct)" \
  || fail "~/.config/claude still exists — remove it: rm ~/.config/claude"

# ── 8. MCP ───────────────────────────────────────────────────────────────────
# install.sh registers the `obsidian` MCP server (user scope) when
# HOLOCRON_MEMORY_DIR is set — check that directly rather than the
# project-level enabledMcpjsonServers list, which is a different mechanism
# (per-project .mcp.json opt-in) that this repo doesn't otherwise depend on.

section "8. MCP"

if command -v claude &>/dev/null; then
  if claude mcp list 2>&1 | grep -q "obsidian:"; then
    ok "obsidian MCP server registered (user scope)"
  else
    fail "obsidian MCP server not registered — run install.sh with HOLOCRON_MEMORY_DIR set"
  fi
else
  info "claude CLI not found on PATH — skipping MCP check"
fi

# ── 9. Algorithm and steering rules ──────────────────────────────────────────

section "9. Algorithm and steering rules"

INSTRUCTIONS_DIR="$HOME/.claude/instructions"

[[ -f "$INSTRUCTIONS_DIR/algorithm.md" ]]      && ok "algorithm.md exists"      || fail "algorithm.md MISSING at $INSTRUCTIONS_DIR/algorithm.md"
[[ -s "$INSTRUCTIONS_DIR/algorithm.md" ]]      && ok "algorithm.md is non-empty" || fail "algorithm.md is empty"
[[ -f "$INSTRUCTIONS_DIR/steering-rules.md" ]] && ok "steering-rules.md exists"      || fail "steering-rules.md MISSING at $INSTRUCTIONS_DIR/steering-rules.md"
[[ -s "$INSTRUCTIONS_DIR/steering-rules.md" ]] && ok "steering-rules.md is non-empty" || fail "steering-rules.md is empty"
grep -q "algorithm.md"      ~/.claude/CLAUDE.md 2>/dev/null && ok "CLAUDE.md references algorithm.md"      || fail "CLAUDE.md does not reference algorithm.md"
grep -q "steering-rules.md" ~/.claude/CLAUDE.md 2>/dev/null && ok "CLAUDE.md references steering-rules.md" || fail "CLAUDE.md does not reference steering-rules.md"
grep -Eq "Claude Code tools|pi tools" "$INSTRUCTIONS_DIR/algorithm.md" 2>/dev/null && ok "algorithm.md has labeled per-harness tool tables" || fail "algorithm.md missing the labeled Claude Code / pi tool tables"

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "════════════════════════════════════════════════════"
echo "  Results: $PASS passed  |  $FAIL failed  |  $INFO info"
echo "════════════════════════════════════════════════════"

[[ $FAIL -gt 0 ]] && exit 1 || exit 0
